import numpy as np
import pandas as pd
import pytest

from mmsim import Params, AvellanedaStoikov, Symmetric, exact_moments, sampling_se
from mmsim.empirical import Seconds, to_seconds, fill_probability, fit_intensity, backtest, adverse_move

P = Params(s0=1000.0, T=600, dt=1.0, sigma=2.0, A=0.2, k=0.5, noise="gaussian")


def synthetic_seconds(p, n, seed):
    """Seconds generated by the model's own mechanism: the price is a random walk, and in each second an aggressive
    buy (sell) arrives with probability A and reaches an exponential depth with mean 1/k beyond the price, so
    P(a quote at distance delta >= 0 is reached) = A * exp(-k * delta). Fills carry no information."""
    rng = np.random.default_rng(seed)
    s_end = p.s0 + np.cumsum(p.sigma * rng.standard_normal(n))
    s = np.r_[p.s0, s_end[:-1]]
    hi = np.where(rng.random(n) < p.A, s + rng.exponential(1 / p.k, n), np.nan)
    lo = np.where(rng.random(n) < p.A, s - rng.exponential(1 / p.k, n), np.nan)
    return Seconds(s=s, s_end=s_end, hi=hi, lo=lo)


def test_to_seconds_by_hand():
    trades = pd.DataFrame({"price": [100.0, 99.0, 101.0], "t": [0.2, 0.5, 2.1], "buy": [True, False, True]})
    sec = to_seconds(trades, n=4)
    np.testing.assert_array_equal(sec.s_end, [99, 99, 101, 101])
    np.testing.assert_array_equal(sec.s, [100, 99, 99, 101])
    np.testing.assert_array_equal(sec.hi, [100, np.nan, 101, np.nan])
    np.testing.assert_array_equal(sec.lo, [99, np.nan, np.nan, np.nan])


def test_calibration_recovers_model_parameters():
    sec = synthetic_seconds(P, 400_000, seed=1)
    deltas = np.arange(0.25, 12, 0.25)
    pa, pb = fill_probability(sec, deltas)
    A, k = fit_intensity(deltas, (pa + pb) / 2)
    assert A == pytest.approx(P.A, rel=0.03)
    assert k == pytest.approx(P.k, rel=0.03)
    assert np.std(sec.s_end - sec.s) == pytest.approx(P.sigma, rel=0.01)


@pytest.mark.parametrize("which", ["inventory", "symmetric"])
def test_backtest_accounting_identity(which):
    sec = synthetic_seconds(P, 60 * 600, seed=2)
    strat = AvellanedaStoikov(0.01) if which == "inventory" else Symmetric.matching(0.01, P)
    r = backtest(strat, sec, P, tick=0.01)
    assert r.pnl.size == 60
    np.testing.assert_allclose(r.pnl, r.spread_pnl + r.inventory_pnl, atol=1e-6)


def test_backtest_on_model_data_matches_exact_solution():
    """On data generated by the model itself, the backtest must reproduce the model's exact predictions."""
    strat = Symmetric(spread=4.0)                     # constant distance 2 > 0, where synthetic fills follow A*exp(-k*delta)
    n_ep = 3000
    r = backtest(strat, synthetic_seconds(P, n_ep * 600, seed=3), P, tick=1e-9)
    ex = exact_moments(strat, P)
    se = sampling_se(ex, n_ep)
    assert abs(r.pnl.mean() - ex["mean_pnl"]) < 4 * se["mean_pnl"]
    assert abs(r.pnl.std() - ex["std_pnl"]) < 4 * se["std_pnl"]
    assert abs(r.q.std() - ex["std_q"]) < 4 * se["std_q"]
    assert r.n_trades.mean() == pytest.approx(ex["mean_trades"], rel=0.01)


def test_no_adverse_move_on_uninformative_fills():
    sec = synthetic_seconds(P, 200 * 600, seed=4)
    r = backtest(Symmetric(spread=4.0), sec, P, tick=1e-9, log_trades=True)
    for h in [1, 60]:
        move = adverse_move(sec, r.trades, P.n_steps, h)
        assert abs(move) < 4 * P.sigma * np.sqrt(h) / np.sqrt(r.trades["side"].size)


def test_backtest_requires_one_second_steps():
    with pytest.raises(ValueError):
        backtest(Symmetric(spread=4.0), synthetic_seconds(P, 600, seed=5), P.with_(dt=0.5))
